on:
  push:
    branches:
      - master

name: CI

jobs:
  test:
    name: Run the PHP unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Create the base image
      env:
        IMAGE_TAG: custom-wordpress:5.2.3-php7.2-apache
      run: |
        docker build -t $IMAGE_TAG .

    - name: Start all the services
      run: docker-compose up -d

    - name: Wait 30s for the services to be up and running
      run: sleep 30

    - name: Initialize wordpress and update the plugins
      run: make wordpress

    - name: Install the composer dependencies
      run: make composer

    - name: Configure the unit tests
      run: make phpunit

    - name: Run the unit tests
      run: make test